block: add size as a parameter to vol_copy
open-iscsi/targetd pull request #78
Opened 2021-01-15 16:58 UTC by whywaita

## Change
-  add the `size` parameter to `vol_copy`.

call expand commands after call clone/snapshot volume.

## Background
Now, the `vol_new` created volume size is the same as `vol_orig`. but some cases need to expand `vol_new`.

For example, the OS image. 
`vol_orig` is a base image. size is about 10MB to 500MB. (in Fedora 33 Cloud Base Images is 319MB in qcow2.)[1]
`vol_new` is a volume of the virtual machines. need size is about 1GB too unlimited. It is bigger than the size of `vol_orig`.

So, need `size` parameter in `vol_copy`.

[1]: https://alt.fedoraproject.org/cloud/

2021-01-15 17:05 UTC, whywaita commented
Oh, I forget to fix tests. I will fix it.

2021-01-15 20:11 UTC, whywaita commented
Hi @tasleson !
I fixed tests on targetd.
I see to pass all tests on targetd, but fail tests on libstoragemgmt now.

I found some commits that move a path of plugins on libstoragemgmt by @tasleson. (e.g. https://github.com/libstorage/libstoragemgmt/pull/448 )
Can you check Travis CI?

2021-01-19 23:23 UTC, tasleson commented
> Hi @tasleson !
> I fixed tests on targetd.
> I see to pass all tests on targetd, but fail tests on libstoragemgmt now.
> 
> I found some commits that move a path of plugins on libstoragemgmt by @tasleson. (e.g. [libstorage/libstoragemgmt#448](https://github.com/libstorage/libstoragemgmt/pull/448) )
> Can you check Travis CI?

@whywaita  Just getting back from a holiday, I'll take a look at all this tomorrow, thanks!

2021-01-20 17:21 UTC, whywaita commented
@tasleson nice a holiday! 👍
please check it after 🙏

2021-01-21 20:43 UTC, tasleson commented
@whywaita https://github.com/open-iscsi/targetd/pull/79 gets CI to work again, please pick up the correction and add it to this PR.  I haven't checked the actual changes in this PR and will do so tomorrow, thanks!

2021-01-22 02:28 UTC, whywaita commented
@tasleson Thanks for your great work!
I cherry-picked your commit. CI become pass!

2021-01-22 22:10 UTC, tasleson requested changes
Overall this looks fine.  Before we commit I think it would be good to squash it a bit, as I don't think we need the intermediate steps of using a string for size and then moving to a numeric.

Some things to consider before incorporating

* Size domain, should we require size to be > current size?
* Block device sizes typically need to be on some block size boundary, eg. if a user specifies a 1 byte size increase, should we reject, roundup etc.?  What is the most compatible way with all the different back ends?

2021-01-22 22:13 UTC, tasleson commented
@dsonck92 Any thoughts on this proposed API change?

2021-01-22 22:15 UTC, tasleson commented on test/targetd_test.py
> +            TestTargetd._vol_copy(block_pool, vol, vol_copy_name, expanded_size)
I think it would it be better to use `vol.size + some_size_increase` instead of specifying an entire new value here.  That way if `_vol_create` changes it's base size we don't get into an issue where `expanded_size` no longer makes sense.

2021-01-23 16:13 UTC, whywaita commented on API.md
> +Resize a new volume if set `size` after created.
fixed in https://github.com/open-iscsi/targetd/pull/78/commits/fb029a17df75719351e48cd8356b66633618a759

2021-01-23 16:14 UTC, whywaita commented on client
> +                        dict(pool=pool, vol_orig="test2", vol_new="test2-copy", size="%dG" % str(8*1024*1024)))
fixed in https://github.com/open-iscsi/targetd/pull/78/commits/6cab8ec51ff29f962125f8c411befb6462ae92ac

2021-01-23 16:14 UTC, whywaita commented on test/targetd_test.py
> +            TestTargetd._vol_copy(block_pool, vol, vol_copy_name, expanded_size)
fixed in https://github.com/open-iscsi/targetd/pull/78/commits/311a61950aead68820b9fb3570e4787b94c27d20

2021-01-23 16:24 UTC, whywaita commented
> Size domain, should we require size to be > current size?
yes. I will implement it after.

> Block device sizes typically need to be on some block size boundary, eg. if a user specifies a 1 byte size increase, should we reject, roundup etc.? What is the most compatible way with all the different back ends?
I think that check should delegate to backends with all backends.
resize parameter is many expressions in a storage controller in the world.
So I passed through "size" to backends.

2021-01-23 17:05 UTC, whywaita commented
I squashed some commits!

2021-01-25 09:44 UTC, dsonck92 commented on targetd/backends/zfs.py
> +         code, out, err = _zfs_exec_command(["set",
You probably want to do the resize during the clone with `-o volsize=%d` directly. There was a bug on FreeBSD which had issues with resizing a cloned zvol after cloning which didn't happen when it was done atomically. Now I know this is specific for FreeBSD whereas targetd likely doesn't target it, but this way it's also atomic.

2021-01-25 09:46 UTC, dsonck92 commented
@tasleson I think this should be fine considering it's an optional addition and API users should be using named arguments. So as long as they use named arguments, this should be fine. And those that use the positional arguments should be fine as long as they didn't customize the timeout. But again, they should not be using the positional argument style.

2021-01-25 14:12 UTC, whywaita commented on targetd/backends/zfs.py
> +         code, out, err = _zfs_exec_command(["set",
@dsonck92 Thanks, good suggestion! I have set `-o volsize` in `https://github.com/open-iscsi/targetd/pull/78/commits/32782859e83610cde3c1e461f80508758e2e932f`.

2021-01-25 16:16 UTC, tasleson commented on targetd/block.py
> +            if v['name'] == vol_orig and v['size'] > size:
I believe this should be `>=`

2021-01-25 16:18 UTC, tasleson commented on targetd/block.py
> +                                   "Size %d need a larger than size in original volume %s in pool %s" % (size,
Please add a test which causes this error path to be executed.

2021-01-25 16:21 UTC, tasleson requested changes
Please address comments and we can get this merged.

Thank you!

2021-01-25 17:20 UTC, whywaita commented on targetd/block.py
> +            if v['name'] == vol_orig and v['size'] > size:
fixed in https://github.com/open-iscsi/targetd/pull/78/commits/0ab35ed805a82182a17d6bb659ef81ad749efb9d

2021-01-25 17:20 UTC, whywaita commented on targetd/block.py
> +                                   "Size %d need a larger than size in original volume %s in pool %s" % (size,
I added two tests in https://github.com/open-iscsi/targetd/pull/78/commits/0ab35ed805a82182a17d6bb659ef81ad749efb9d

2021-01-25 18:50 UTC, merged

2021-01-25 18:51 UTC, tasleson commented
@whywaita Thank you

2021-01-25 18:51 UTC, tasleson commented
> @tasleson I think this should be fine considering it's an optional addition and API users should be using named arguments. So as long as they use named arguments, this should be fine. And those that use the positional arguments should be fine as long as they didn't customize the timeout. But again, they should not be using the positional argument style.

@dsonck92 Thanks for reviewing this!

2021-01-26 01:06 UTC, whywaita commented
@tasleson @dsonck92 Thanks you!